[package]
name = "kemeleon"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "doc/katex-header.html",
]

[features]
deterministic = ["ml-kem/deterministic"]

[dependencies]
byteorder = "1.5.0"
num-bigint = "0.4.6"
rand = "0.8.5"
ml-kem = { version="0.2.1" }
hybrid-array = "0.2.0-rc.8"
rand_core = "0.6.4"
kem = "0.3.0-pre.0"

hex = "0.4.3"

[dev-dependencies]
hex-literal = "0.4.1"

