[package]
name = "kemeleon"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "doc/katex-header.html",
]

[features]
default=[]
deterministic = ["ml-kem/deterministic"]

[dependencies]
num-bigint = "0.4.6"
rand = "0.8.5"
ml-kem = { version="0.2.1" }
hybrid-array = "0.2.0-rc.8"
rand_core = "0.6.4"
kem = "0.3.0-pre.0"
lazy_static = "1.5.0"

# hmac-drbg
hmac = "0.12.1"
digest = "0.10.7"
generic-array = "0.14.7"
sha2 = "0.10.8"

[dev-dependencies]

hex =  { version = "0.4.3", features = ["serde"] }
hex-literal = "0.4.1"
num-rational = "0.4.2"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
